# Retrieves the current configuration (joint position) of the requested planning group

# The planning group name
string group_name

---

# The joint values of the group. Will have 0 elements if lookup failed
float64[] positions

---

# No distinct feedback message 
